config/routes.rb
Kerweb::Application.routes.draw do

    namespace :mercury do
      resources :images
    end

  mount Mercury::Engine => '/'

  root :to => 'Home#index'

  resources :projects
  resources :posts, only: [:index, :show, :update], path: 'blog'  do
    member { put :mercury_update }
  end

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

	get "home/index"

	post '/formPost' => 'Home#formPost'

end

app/models/mercury/image.rb
class Mercury::Image < ActiveRecord::Base

  self.table_name = :mercury_images

  attr_accessible :image

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
        :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
        :url => "/system/:attachment/:id/:style/:filename"

  delegate :url, :to => :image

  def serializable_hash(options = nil)
    options ||= {}
    options[:methods] ||= []
    options[:methods] << :url
    super(options)
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  attr_accessible :name, :email, :body, :state

  STATES = %w(new viewed)

  #validates_inclusion_of :state, :in => STATES
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :preview, :title
  validates :title, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :body, :href, :name, :picture, :picture_mini, :position

  acts_as_list

  has_attached_file :picture,
	  :styles => { :fit => "800x" },
	  :default_url => "system/images/:style/missing.png",
	  :url => "system/images/:style/:filename",
	  :path => "public/system/images/:style/:filename"

  has_attached_file :picture_mini,
	  :styles => { :mini => "250x185!" },
	  :default_url => "system/images/:style/missing",
	  :url => "system/images/:style/:filename",
	  :path => "public/system/images/:style/:filename"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		I18n.locale = params[:locale]
		@notice = params[:notice]
		@title = 'Студия разработки Kernel Web'
		@projects = Project.order("position ASC").all
	end
	
	def landing
		render layout: 'landing'
	end

	def formPost
		@offer = Offer.new params[:offer]
		@offer.state = 'new'
		notice = if @offer.save then t 'notice.success' else t 'notice.failure' end
		redirect_to "/", :notice => notice
	end
end

app/controllers/mercury/images_controller.rb
class Mercury::ImagesController < MercuryController

  respond_to :json

  # POST /images.json
  def create
    @image = Mercury::Image.new(params[:image])
    @image.save
    respond_with @image
  end

  # DELETE /images/1.json
  def destroy
    @image = Mercury::Image.find(params[:id])
    @image.destroy
    respond_with @image
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").all
    respond_to do |format|
      format.html
      format.json {render json: @posts}
    end
  end

  def show
    @post = Post.find params[:id]
    respond_to do |format|
      format.html
      format.json {render json: @post}
    end
  end

  def mercury_update
    @post = Post.find(params[:id])
    @post.title   = params[:content][:title][:value]
    @post.preview = params[:content][:preview][:value]
    @post.body    = params[:content][:body][:value]
    @post.save!
    render text: ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_head.html.haml
%head
  %title #{@title}
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %meta{:charset => "utf-8"}
  %meta{:content => "Cтудия разработки Kernel Web. Разработка веб-сервисов любой сложности на Ruby on Rails. Landing pages, интернет-магазины, корпоративные порталы, CRM и ERP решения", :name => "description"}
  %meta{:content => "Cтудия разработки Kernel Web", :name => "author"}
  %meta{:content => "Kernel, студия разработки Kernel Web, веб-студия, веб, программирование, разработка, Ruby, технопарк, IT, Ruby On Rails, Rails, Redmine, CRM, ERP, programming, coding",
  :name => "keywords"}
  / Facebook Metadata /
  %meta{:content => "kernelweb", :property => "fb:page_id"}
  %meta{:content => "", :property => "og:image"}
  %meta{:content => "Cтудия разработки Kernel Web. Разработка веб-сервисов любой сложности на Ruby on Rails. Landing pages, интернет-магазины, корпоративные порталы, CRM и ERP решения", :property => "og:description"}
  %meta{:content => "Cтудия разработки Kernel Web", :property => "og:title"}
  / Google+ Metadata /
  %meta{:content => "студия разработки Kernel Web", :itemprop => "name"}
  %meta{:content => "Cтудия разработки Kernel Web. Разработка веб-сервисов любой сложности на Ruby on Rails. Landing pages, интернет-магазины, корпоративные порталы, CRM и ERP решения", :itemprop => "description"}
  %meta{:content => "", :itemprop => "image"}
  %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1", :name => "viewport"}
  / Stylesheet /
  = stylesheet_link_tag 'bootstrap.min'
  = stylesheet_link_tag 'bootstrap-responsive.min.css'
  = stylesheet_link_tag 'kerweb'
  = stylesheet_link_tag 'prettyPhoto'
  = stylesheet_link_tag 'gumby'
  = stylesheet_link_tag 'media'
  = stylesheet_link_tag 'style'
  = stylesheet_link_tag 'stylesOnHtml'
  = stylesheet_link_tag 'fonts'
  = stylesheet_link_tag 'project_pics_filter'
  = stylesheet_link_tag 'parallaxe'
  = stylesheet_link_tag 'about_us'
  = javascript_include_tag 'modernizr.custom.js'
  = javascript_include_tag 'jquery.min'
  = javascript_include_tag 'bootstrap.min'
  = javascript_include_tag 'kerweb'
  = javascript_include_tag 'jaslide'
  = javascript_include_tag 'jquery.prettyPhoto'
  = javascript_include_tag 'home.js.coffee'
  = javascript_include_tag 'logo_load.js.coffee'
  = javascript_include_tag 'about_us.js.coffee'

app/views/home/_vk_body.erb
<div id="vk_comments"></div>
<script type="text/javascript">
  VK.Widgets.Comments("vk_comments", {limit: 10, width: "520", attach: "*"});
</script>

app/views/home/_vk_head.erb
<!-- Put this script tag to the <head> of your page -->
<script type="text/javascript" src="//vk.com/js/api/openapi.js?101"></script>

<script type="text/javascript">
  VK.init({apiId: 3912210, onlyWidgets: true});
</script>

app/views/home/index.html.haml
/ HEADER HOME ###############################################
#logo-bg
%section#home
    %table{id: 'logo_table'}
        %tr.js_height
            %td.js_width
            %td
            %td.js_width
        %tr
            %td.js_width
            %td
                #logo_text
                    #kernel_web
                        Kernel Web
                    #dev_studio
                        студия разработки
            %td.js_width
                #logo_img>
                    %img{src: "assets/logo_img.png"}>
                #logo_arrows>
        %tr.js_height
            %td.js_width
            %td
            %td.js_width
/ LITTLE LOGO SEE WHAT WE DO
#down_button.fade-it
    %a{:href => "#about_us"}
/ END LITTLE LOGO SEE WHAT WE DO
/ END HEADER HOME ###############################################
/ NAVIGATION ###############################################
.nav-container{:style => "height: auto;"}
    %nav{:style => "top: 0px;"}
        #logo
            %a{:href => "#home"}
                %table
                    %td
                        #text_head
                            Kernel<br>Web
                        студия<br>разработки
                    %td
                        %img{:alt => "Kerweb", :src => "/assets/logo_img.png"}
        %ul
            %li
                %a{:href => "#about_us"}
                    О нас
            %li
                %a{:href => "#whatwedo"}
                    =t 'what_we_do.title'
            %li
                %a{:href => "#contact"}
                    =t 'contacts.title'
/ END NAVIGATION ###############################################
/ THREE RECTANGLES ABOUT US ###############################################
%section#about_us
    ._row#_red
        ._fon
        .row
            ._holder
                ._content
                    ._text
                        С нашей помощью вы получите удобный сайт, который понравится
                        вашим клиентам. Простой блог или интернет-магазин с широким
                        набором функций – мы найдем подход к наилучшему решению любой
                        задачи. Ваш сайт станет не просто информационной площадкой,
                        но эффективным инструментом для развития и продвижения бизнеса.
                ._rectangle
                    %img._icon{ src: '/assets/about_us/icon_red.png' }
                    ._info
                        ._title Разработка сайтов
                        ._points 
                            Сайты-визитки <br>
                            Корпоративные порталы <br>
                            Интернет-магазины <br>
                            Интернет-журналы <br>
                            Веб-приложения
    ._row#_blue.left
        .row
            ._holder
                ._rectangle
                    %img._icon{ src: '/assets/about_us/icon_blue.png' }
                    ._info
                        ._title Увеличение <br> эффективности бизнеса
                        ._points
                            Автоматизация процессов <br>
                            Системы управления качеством <br>
                            Новые рекламные площадки <br>
                            Снижение нагрузки на операторов
                ._content
                    ._text
                        Ищете новые способы оптимизации своего бизнеса? Нам есть, что вам
                        предложить. Автоматизация некоторых процессов поможет
                        освободить время и умы ваших сотрудников для более важных дел.
                        Поисковая оптимизация и рекламные площадки откроют ваш бизнес для новых клиентов.
    ._row#_green
        ._fon
        .row
            ._holder
                ._rectangle
                    %img._icon{ src: '/assets/about_us/icon_green.png' }
                    ._info
                        ._title Повышение лояльности <br> ваших клиентов
                        ._points 
                            Автоматизация приема заказов <br>
                            E-mail, sms уведомления <br>
                            Внедрение дополнительных <br>
                            сервисов

                ._content
                    ._text
                        Мы заинтересованы в том, чтобы ваши клиенты были довольны.
                        Основная цель – получить сайт, с которым будет легко и приятно
                        общаться каждому посетителю. Для этого мы используем инструменты
                        автоматизации, настраиваем уведомления и внедряем
                        дополнительные сервисы, а вы получаете быструю обратную связь от
                        потребителя.

/ END THREE RECTANGLES ABOUT US ###############################################
/ WHAT WE DO SECTION ###############################################
%section#whatwedo
    .row
        .twelve.columns.centered
            %h2
                = t 'what_we_do.title'
                %i.title_line
    .row
        / WORKS GRID
        %ul#og-grid.og-grid
            - @projects.each do |project|
                = render 'projects/miniproject', :project => project
        / END WORKS GRID
/ END WHAT WE DO SECTION ###############################################
/ CONTACT SECTION ###############################################
%section#contact
    .row
        .twelve.columns.centered
            %h2
                =t 'contacts.title'
                %i.title_line
    .row
        .eleven.columns.centered
            %p.subtittle
                =t 'contacts.greeting_clients.html'
    .row
        .seven.columns
            %form{:action => "/formPost", :method => "post", :name => "offerForm", :enctyoe => "multipart/form-data"}
                %input{:name => "offer[name]", :placeholder => t('placeholder.first_name'), :required => "", :type => "text"}/
                %input{:name => "offer[email]", :placeholder => t('placeholder.email'), :required => "", :type => "email"}/
                %textarea{:cols => "1", :name => "offer[body]", :placeholder => t('placeholder.textarea'), :required => "", :rows => "5"}
                %button.submit{:name => "send", :type => "submit"}
                    =t 'placeholder.submit'
        .five.columns.info
            %h4
                =t 'contacts.where_can_find'
            =t 'contacts.address.html'
            %h4
                =t 'contacts.contact_us'
            %p
                Телефон: +7-383-213-46-79
            %p
                e-mail:
                %a{:href => "mail"}
                    hello[at]kerweb.ru
            %p
                skype:
                %a{:href => "skype:shabalinsky?chat"} shabalinsky

/ END CONTACT SECTION ###############################################
/ TWITTER MODULE ###############################################
/%section#twitter_module
/	.row
/		.twelve.columns
/			#ticker.query
/				%ul.tweet_list
/					%li.tweet_even
/ END TWITTER MODULE ###############################################
/ SOCIAL MODULE ###############################################
%section#social_module
    .row
        .twelve.columns
            %ul
                %li
                    %a{:href => "https://twitter.com/kernelweb", :target => "_blank"}
                        %i.icon
                            L
                %li
                    %a{:href => "https://facebook.com/kernelweb", :target => "_blank"}
                        %i.icon
                            F
                %li
                    %a{:href => "https://vk.com/kernelweb", :target => "_blank"}
                        %i.icon.vk
                            B

/ END SOCIAL MODULE ###############################################
- if @notice
    %div.modal
        %p= @notice
/ MAP ########################################################
%section#map{style: 'height: 600px'}
    -#%a{:id=> "firmsonmap_biglink", :href=>"http://maps.2gis.ru/#/?history=project/novosibirsk/center/83.110517887677,54.857621924391/zoom/18/state/widget/id/141266769615561/firms/141266769615561"} Перейти к большой карте
    %div{id: "myMapId", style: "width:100%; height:620px"}
    -#%script{:charset=>"utf-8", :type=>"text/javascript", :src=>"http://firmsonmap.api.2gis.ru/js/DGWidgetLoader.js"}
    :javascript
        DG.autoload(function() {
                // Создаем объект карты, связанный с контейнером:
                var myMap = new DG.Map('myMapId');
                myMap.disableScrollZoom();
                // Устанавливаем центр карты и коэффициент масштабирования:
                myMap.setCenter(new DG.GeoPoint(83.110517887677,54.857621924391),16);
                // Добавляем элемент управления коэффициентом масштабирования:
                myMap.controls.add(new DG.Controls.Zoom());
                var myBalloon = new DG.Balloons.Common({
                    // Местоположение на которое указывает балун:
                    geoPoint: new DG.GeoPoint(83.110417887679,54.858021924395),
                    // Устанавливаем текст, который будет отображатся при открытии балуна:
                    contentHtml: 'Центр информационных технологий новосибирского Академпарка<br>Николаева 11, офис 407<br> Cтудия разработки Kernel Web'
                });
                // Создаем маркер:
                var myMarker = new DG.Markers.Common({
                    // Местоположение на которое указывает маркер:
                    geoPoint: new DG.GeoPoint(83.110417887679,54.858021924395),
                    // Функция, вызываемая при клике по маркеру
                    clickCallback: function() {
                        if (! myMap.balloons.getDefaultGroup().contains(myBalloon)) {
                            // Если балун еще не был добавлен на карту, добавляем его:
                            myMap.balloons.add(myBalloon);
                        } else {
                            // Показываем уже ранее добавленный на карту балун
                            myBalloon.show();
                        }
                    }
                });
                 myMap.balloons.add(myBalloon);
                 myBalloon.show();
                // Добавить маркер на карту:
                myMap.markers.add(myMarker);
            });
        //new DGWidgetLoader({"borderColor":"#a3a3a3","width":"100%","height":"600","wid":"283e085a9fc3da107605cd457815ac06","pos":{"lon":"83.110517887677","lat":"54.857621924391","zoom":"16"},"opt":{"ref":"hidden","card":["name","contacts","schedule","payings","flamp"],"city":"novosibirsk"},"org":[{"id":"141266769615561"}]});
    %noscript {:style=>"color:#c00;font-size:16px;font-weight:bold;"} Виджет карты использует JavaScript. Включите его в настройках вашего браузера


/ FOOTER ###############################################
%footer
    .row
        .twelve.columns
            %p
                = "©#{DateTime.now.year} студия разработки Kernel Web. All rights reserved."
                
                
/            %img{:alt => "YOURLOGO", :src => "/assets/logo_small.png"}/
/ END FOOTER ###############################################
- if !notice.blank?
    %div.modal
        = notice
/ JAVASCRIPTS ###############################################
%script{:src => "/assets/jquery-1.9.1.min.js", :type => "text/javascript"}
%script{:src => "/assets/jquery.scrollto.js"}
%script{:src => "/assets/waypoints.min.js", :type => "text/javascript"}
%script{:src => "/assets/jquery.tweet.js", :type => "text/javascript"}
%script{:src => "/assets/scripts.js", :type => "text/javascript"}
%script{:src => "/assets/grid.js"}
%script{id: "top100Counter", type: "text/javascript", src: "http://counter.rambler.ru/top100.jcn?2925357"}
%noscript
    %a{href: "http://top100.rambler.ru/navi/2925357/"}
    %img{src: "http://counter.rambler.ru/top100.cnt?2925357", alt: "Rambler's Top100", border: "0"}

/ END JAVASCRIPTS ###############################################

app/views/layouts/application.html.haml
!!!
%html
  = render 'home/head'
  %script{type: "text/javascript", src: "http://maps.api.2gis.ru/1.0"}

%body
  = yield
%script{src: "//converzilla.kerweb.ru/assets/public.js", type:"text/javascript"}
:coffee
  new Converzilla('542e36c470726f360f000000', {exitForm: false, visitors: true})
-#Yandex Метрика
:javascript
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter22592101 = new Ya.Metrika({id:22592101,
          webvisor:true,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true});
      } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
      s = d.createElement("script"),
      f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
%noscript
  %div
    %img{:src => "//mc.yandex.ru/watch/22592101", :style => "position:absolute; left:-9999px;", :alt => ""}
-#Google Analytics
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42469013-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
:javascript
  var _tmr = _tmr || [];
  _tmr.push({id: '2381492', type: 'pageView', start: (new Date()).getTime()});
  (function (d, w) {
     var ts = d.createElement('script'); ts.type = 'text/javascript'; ts.async = true;
     ts.src = (d.location.protocol == 'https:' ? 'https:' : 'http:') + '//top-fwz1.mail.ru/js/code.js';
     var f = function () {var s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ts, s);};
     if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
  })(document, window);
:javascript
  document.write("<a href='http://www.liveinternet.ru/click' "+
  "target=_blank><img style='display: none;' src='//counter.yadro.ru/hit?t44.1;r"+
  escape(document.referrer)+((typeof(screen)=="undefined")?"":
  ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
  screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
  ";"+Math.random()+
  "' alt='' title='LiveInternet'"+
  "border='0' width='31' height='31'><\/a>")

app/views/layouts/posts.html.haml
!!!
%html
  %title
    =yield :title
  %meta{:content => yield(:description), :name => "description"}

  = stylesheet_link_tag 'bootstrap.min'
  = stylesheet_link_tag 'bootstrap-responsive.min.css'
  = stylesheet_link_tag 'kerweb'
  = stylesheet_link_tag 'prettyPhoto'
  = stylesheet_link_tag 'media'
  = stylesheet_link_tag 'style'
  = stylesheet_link_tag 'stylesOnHtml'
  = javascript_include_tag 'kerweb'
  = javascript_include_tag 'posts'
  = render partial: 'home/vk_head'

%body.posts
  .nav-container{:style => "height: auto;"}
    %nav{:style => "top: 0px;"}
      #logo
        %img{:alt => "Kerweb", :src => "/assets/logo_small.png"}
      %ul
        %li
          %a{:href => '/', 'data-no-turbolink' => true}
            =t 'to_home'
        %li
          =link_to 'Все посты', posts_path
  .posts
    .container
      = yield
-#/ FOOTER ###############################################
-#%footer
-#  .row
-#    .twelve.columns
-#      %a{:href => '/', 'data-no-turbolink' => true}
-#        %img{:alt => "YOURLOGO", :src => "/assets/logo_footer.png", }

app/views/posts/index.html.haml
- content_for :title do
  ='Посты'
- content_for :description do
  ='Посты блога компании Kerweb. Преимущественно по веб программированию'

-@posts.each do |post|
  .post
    %h3
      = link_to raw(post.title), post
    #preview
      =raw post.preview unless post.preview.blank?

app/views/posts/show.html.haml
- content_for :title do
  =raw @post.title
- content_for :description do
  =@post.preview

%h1#title{'data-mercury' => 'simple'}
  =raw @post.title
#preview{'data-mercury' => 'full'}
  =raw @post.preview unless @post.preview.blank?
#body{'data-mercury' => 'full'}
  =raw @post.body unless @post.preview.blank?
= render partial: 'home/vk_body'

-if current_user
  =link_to "Edit",  "/editor" + request.path, id: "edit_link", data: {save_url: mercury_update_post_path},
  style: 'display: none'

app/views/projects/_miniproject.html.haml
%li
	%a{"data-description" => project.body, "data-largesrc" => project.picture.url(:fit), "data-title" => project.name, :href => project.href}
		%img.mini_project_img{ :src => project.picture_mini.url(:mini), :alt => project.name }